views/intro_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect
from models import Question

bp = Blueprint('intro', __name__, url_prefix='/')

@bp.route('/')
def main():
    return render_template('intro.html')

@bp.route('/linux')
def linux():
    return render_template('notion/linux.html')

@bp.route('/aws')
def aws():
    return render_template('notion/aws.html')

@bp.route('/docker')
def docker():
    return render_template('notion/docker.html')

@bp.route('/kubernetes')
def kubernetes():
    return render_template('notion/kubernetes.html')

@bp.route('/cicd')
def cicd():
    return render_template('notion/cicd.html')

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Goorm_KU</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</head>

<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>

</html>

templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

templates/intro.html
{% extends 'base.html' %}
{% block content %}
<div class="flex-container">
    <div class="flex-item">
        <div class="container-body-title">Ku_PROJECT</div>
        <div class="container-body-sub">
            04/22 ~ 8/17<br>Goorm with KakaoEnterprise<br>
        </div>
    </div>
    <div class="flex-item-login">
        <div class="container-body-title">Ku_PROJECT</div>
        <div class="container-body-sub">
            04/22 ~ 8/17<br>Goorm with KakaoEnterprise<br>
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
<nav>
    <div class="header">
        <div class="container clearfix">
            <div class="container-left clearfix">
                <div class="logo">
                    <a href="{{ url_for('intro.main') }}"><img
                            src="{{ url_for('static', filename='image/goorm.png') }}"></a>
                </div>
                <div class="menu clearfix">
                    <a href="/linux" class="menu-item">Linux</a>
                    <a href="/cicd" class="menu-item">CI/CD</a>
                    <a href="/docker" class="menu-item">Docker</a>
                    <a href="/kubernetes" class="menu-item">Kubernetes</a>
                    <a href="/aws" class="menu-item">Aws</a>
                    <a href="/main/kk" class="menu-item">게시판</a>
                </div>
                <div class="container-right">
                    {% if g.user %}
                    {{ g.user.username }}님
                    <button type="button" class="myButton" onclick="location.href='/auth/logout'">logout</button>
                    {% else %}
                    <button type="Button" class="myButton" onclick="location.href='/auth/login'">Login</button>
                    <button type="Button" class="myButton" onclick="location.href='/auth/signup'">signup</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>